[metadata]
name = openfga-cli-py
version = 0.7.20.0
description = Python wrapper around invoking the OpenFGA CLI (https://github.com/openfga/cli)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/neeve-ai/openfga-cli-py
author = oss-robin
license = Apache License Version 2.0
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
python_requires = >=3.11
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [fga]
    group = fga-binary
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_linux_amd64.tar.gz
    sha256 = f0136868bdced6f8fded1876d41aa8d594d23588183497f6d876c1a5343529a4
    extract = tar
    extract_path = fga
    [fga]
    group = fga-binary
    marker = sys_platform == "linux" and platform_machine == "aarch64"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_linux_arm64.tar.gz
    sha256 = 6acb3158fd46fa706344664df9a1d9433d9ec6322044bdcbf952126e7e098760
    extract = tar
    extract_path = fga
    [fga]
    group = fga-binary
    marker = sys_platform == "linux" and platform_machine == "i686"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_linux_386.tar.gz
    sha256 = 91c5fc82e5cf90a2f35f7e9f3500cf04166ab8452f5838065e66933655b05804
    extract = tar
    extract_path = fga
    [fga]
    group = fga-binary
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_darwin_amd64.tar.gz
    sha256 = 0be76e333e6970546300f1e1ff22d599351a65e09879292b0dc79af8d4aa6d19
    extract = tar
    extract_path = fga
    [fga]
    group = fga-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_darwin_arm64.tar.gz
    sha256 = f481da61d4a2dee8dac279227401f9ecbe5bdb051c546bf64c1d4e9c027b1ba3
    extract = tar
    extract_path = fga
    [fga.exe]
    group = fga-binary
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_windows_amd64.tar.gz
    sha256 = 525eaa1b1a6870f217a8b8ef2dfddff8560dac8582e392838381a65411496030
    extract = tar
    extract_path = fga.exe
    [fga.exe]
    group = fga-binary
    marker = sys_platform == "win32" and platform_machine == "ARM64"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_windows_arm64.tar.gz
    sha256 = 931d98b4dca951fa19164abbbe463704adc1fbfc9c3d308225b7bfe1f14f76ae
    extract = tar
    extract_path = fga.exe
    [fga.exe]
    group = fga-binary
    marker = sys_platform == "win32" and platform_machine == "x86"
    url = https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_windows_386.tar.gz
    sha256 = 5d244ad4f444c3f001036fa1599d1308507a2f3de6c7ae325a3a6d9204486a20
    extract = tar
    extract_path = fga.exe
